# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4e042d7a31b70bf6f315663c3f5de344d5a6949ea842c1fc62f1683c3fcdd05e577d3f4b36137da7a1a024a20b61a6d5ca2c98a733dac17b579a416531a0ff2

test:
  secret_key_base: 1291eaad16d4efab5aedef159155a7e33f235491715c852fc10743534f6b285ae2209a4f3baf7b726463f58c3d7436ae16f71ab85e084c5f3cba840918292095

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
